### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by NTULINUX** [zhizhouzh/clfs-arm64#2]
Hello,

I've been working on a rewrite of your bash CLFS tool, what license is your script under?

I'm making quite large modifications to the structyre and would like to know how you'd want to be credited. I have a link to your repository at the top of the bash script, please let me know with more details. I do not want to infringe on copyright and would like to host my changes appropriately.

**Comment by zhizhouzh** [comment]
Hi, I'm glad to know someone else take an interest in this. Actually I didn't consider for this before. I don't want to restrict you by copyright things. I think BSD license is OK. If you are willing to share you code. GPL is fine. For me, I think GPL will be better.

**Comment by NTULINUX** [comment]
All my code is publicly available on here already so I have no problems sharing. If you want to use the GPL license, you'll need to add the appropriate COPYING file (the license file which contains the preamble) and a copyright header / permission statement to your software with your name and email address.

For more info:

https://www.gnu.org/licenses/gpl-howto.en.html

**Comment by NTULINUX** [comment]
Thank you! I have converted my repo to GPLv3 to keep it inline with yours. Closing this issue, thanks again!
