### ISSUE TITLE
GCC and Newlib

### ISSUE THREAD

**Issue by NTULINUX** [zhizhouzh/clfs-arm64#3]
Hi, one thing I noticed in your env_setup.sh file is that you compile the stage1 GCC before GLIBC is built, and that you use --with-newlib in your configure line. Have you tested this yourself? I haven't done a dry-run of the build yet, but last I tried compiling GCC with --with-newlib --without-headers I had compiling errors due to the fact that newlib did not have everything that GCC needed (this was on x86 so aarch64 may be different.) Also, if you do use --with-newlib, how come you don't have newlib compiled? Nowhere in your script does it grab the source code for newlib and compile it, so I'm confused as to how this script could theoretically work.

https://sourceware.org/git/gitweb.cgi?p=newlib-cygwin.git

I have yet to be able to build GCC without GLIBC built first, let alone with newlib. I'd appreciate your feedback on this. Thank you!

**Comment by zhizhouzh** [comment]
@NTULINUX Hi, I'm not for sure what does --with-newlib and --without-headers mean. These build flags is based on mips clfs at [here](http://clfs.org/view/clfs-embedded/mips/cross-tools/gcc-static.html).
I also found some discussion [here](https://gcc.gnu.org/ml/gcc-help/2009-07/msg00368.html). Hope it helps.

**Comment by NTULINUX** [comment]
Thanks! I'll give it a shot.

**Comment by NTULINUX** [comment]
Cross tools builds fine without Glibc or newlib built first, this didn't work for me when building for x86, I also wasn't using sysroot though. Not sure where the magic is but it works fine for aarch64 with sysroot. Closing.
